use std::fs;
use std::path::Path;

use crate::error::Result;
use crate::paths::Paths;
use crate::profile::Profile;

pub const DEFAULT_PATTERNS: &[&str] = &[
    "node_modules/",
    ".git/",
    "target/",
    "dist/",
    ".DS_Store",
    "._*",
    "*.partial",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Action {
    Include,
    Exclude,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FilterRule {
    pub action: Action,
    pub pattern: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct FilterSet {
    pub rules: Vec<FilterRule>,
}

impl FilterSet {
    pub fn from_gitignore_lines<'a, I>(lines: I) -> Self
    where
        I: IntoIterator<Item = &'a str>,
    {
        let mut rules = Vec::new();
        for line in lines {
            push_gitignore_line(&mut rules, line);
        }
        Self { rules }
    }

    pub fn with_defaults(mut self) -> Self {
        for line in DEFAULT_PATTERNS {
            push_gitignore_line(&mut self.rules, line);
        }
        self
    }

    pub fn to_filter_from(&self) -> String {
        let mut out = String::from("# generated by synctr\n");
        for rule in &self.rules {
            let prefix = match rule.action {
                Action::Include => '+',
                Action::Exclude => '-',
            };
            out.push(prefix);
            out.push(' ');
            out.push_str(&rule.pattern);
            out.push('\n');
        }
        out
    }

    pub fn is_excluded(&self, path: &str) -> bool {
        match self.action_for(path) {
            Some(Action::Exclude) => true,
            Some(Action::Include) => false,
            None => false,
        }
    }

    pub fn action_for(&self, path: &str) -> Option<Action> {
        let path = normalize_path(path);
        for rule in &self.rules {
            if rclone_match(&rule.pattern, &path) {
                return Some(rule.action);
            }
        }
        None
    }
}

pub fn load_filters(paths: &Paths, profile: &Profile) -> Result<FilterSet> {
    let mut lines: Vec<String> = Vec::new();
    lines.extend(profile.extra_ignore.iter().cloned());
    append_file_lines(&mut lines, &paths.profile_ignore(&profile.name))?;
    append_file_lines(&mut lines, &paths.ignore_file)?;
    Ok(FilterSet::from_gitignore_lines(lines.iter().map(String::as_str)).with_defaults())
}

fn append_file_lines(lines: &mut Vec<String>, path: &Path) -> Result<()> {
    if !path.is_file() {
        return Ok(());
    }
    for line in fs::read_to_string(path)?.lines() {
        lines.push(line.to_string());
    }
    Ok(())
}

fn push_gitignore_line(rules: &mut Vec<FilterRule>, line: &str) {
    let line = line.trim();
    if line.is_empty() || line.starts_with('#') {
        return;
    }
    let (action, rest) = if let Some(rest) = line.strip_prefix('!') {
        (Action::Include, rest.trim())
    } else {
        (Action::Exclude, line)
    };
    if rest.is_empty() {
        return;
    }
    if let Some(dir) = rest.strip_suffix('/') {
        rules.push(FilterRule {
            action,
            pattern: format!("{dir}/**"),
        });
        rules.push(FilterRule {
            action,
            pattern: format!("{dir}/"),
        });
    } else {
        rules.push(FilterRule {
            action,
            pattern: rest.to_string(),
        });
    }
}

fn normalize_path(path: &str) -> String {
    let mut p = path.replace('\\', "/");
    while p.starts_with("./") {
        p = p[2..].to_string();
    }
    p = p.trim_start_matches('/').to_string();
    p
}

fn rclone_match(pattern: &str, path: &str) -> bool {
    let root = pattern.starts_with('/');
    let pat = pattern.strip_prefix('/').unwrap_or(pattern);
    if root {
        return glob_match(pat, path);
    }
    if glob_match(pat, path) {
        return true;
    }
    for (i, ch) in path.char_indices() {
        if ch == '/' && glob_match(pat, &path[i + 1..]) {
            return true;
        }
    }
    false
}

fn glob_match(pat: &str, text: &str) -> bool {
    glob_at(pat.as_bytes(), 0, text.as_bytes(), 0)
}

fn glob_at(pat: &[u8], pi: usize, text: &[u8], ti: usize) -> bool {
    if pi == pat.len() {
        return ti == text.len();
    }
    if pat[pi] == b'*' && pi + 1 < pat.len() && pat[pi + 1] == b'*' {
        let mut npi = pi + 2;
        if npi < pat.len() && pat[npi] == b'/' {
            npi += 1;
        }
        let mut t = ti;
        loop {
            if glob_at(pat, npi, text, t) {
                return true;
            }
            if t == text.len() {
                return false;
            }
            t += 1;
        }
    }
    if pat[pi] == b'*' {
        let mut t = ti;
        loop {
            if glob_at(pat, pi + 1, text, t) {
                return true;
            }
            if t == text.len() || text[t] == b'/' {
                return false;
            }
            t += 1;
        }
    }
    if pat[pi] == b'?' {
        if ti == text.len() || text[ti] == b'/' {
            return false;
        }
        return glob_at(pat, pi + 1, text, ti + 1);
    }
    if ti < text.len() && pat[pi] == text[ti] {
        return glob_at(pat, pi + 1, text, ti + 1);
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::profile::{Mode, Profile};
    use crate::testutil::scratch;
    use std::path::PathBuf;

    fn defaults() -> FilterSet {
        FilterSet::from_gitignore_lines([]).with_defaults()
    }

    #[test]
    fn node_modules_is_excluded_and_normal_file_is_not() {
        let filters = defaults();
        assert!(
            filters.is_excluded("node_modules/left-pad/index.js"),
            "node_modules path must be excluded"
        );
        assert!(
            filters.is_excluded("src/node_modules/pkg/index.js"),
            "nested node_modules must be excluded"
        );
        assert!(
            !filters.is_excluded("src/lib.rs"),
            "normal source file must not be excluded"
        );
        assert!(!filters.is_excluded("README.md"));
    }

    #[test]
    fn defaults_cover_git_target_dist_ds_store_appledouble_partial() {
        let filters = defaults();
        assert!(filters.is_excluded(".git/config"));
        assert!(filters.is_excluded("crate/target/debug/synctr"));
        assert!(filters.is_excluded("web/dist/bundle.js"));
        assert!(filters.is_excluded(".DS_Store"));
        assert!(filters.is_excluded("dir/.DS_Store"));
        assert!(filters.is_excluded("._Icon"));
        assert!(filters.is_excluded("movie.partial"));
        assert!(!filters.is_excluded("movie.mp4"));
        assert!(!filters.is_excluded(".gitignore"));
    }

    #[test]
    fn user_negation_unexcludes_before_defaults() {
        let filters = FilterSet::from_gitignore_lines(["!node_modules/"]).with_defaults();
        assert!(!filters.is_excluded("node_modules/pkg/index.js"));
        assert!(filters.is_excluded(".git/HEAD"));
    }

    #[test]
    fn extra_ignore_excludes_custom_pattern() {
        let filters = FilterSet::from_gitignore_lines(["secrets/", "*.key"]).with_defaults();
        assert!(filters.is_excluded("secrets/token"));
        assert!(filters.is_excluded("id.key"));
        assert!(!filters.is_excluded("src/main.rs"));
    }

    #[test]
    fn filter_from_uses_rclone_exclude_syntax() {
        let text = defaults().to_filter_from();
        assert!(text.contains("- node_modules/**"));
        assert!(text.contains("- .git/**"));
        assert!(text.contains("- .DS_Store"));
        assert!(text.contains("- ._*"));
        assert!(text.contains("- *.partial"));
    }

    #[test]
    fn load_filters_merges_profile_shared_and_defaults() {
        let (_root, paths) = scratch("ignore-load");
        std::fs::create_dir_all(&paths.profiles_dir).unwrap();
        std::fs::write(paths.profile_ignore("docs"), "*.tmp\n").unwrap();
        std::fs::write(&paths.ignore_file, "build/\n").unwrap();
        let profile = Profile::new(
            "docs".into(),
            PathBuf::from("/tmp/docs"),
            "b2:x".into(),
            Mode::Copy,
            None,
            vec![],
            vec!["*.bak".into()],
        )
        .unwrap();
        let filters = load_filters(&paths, &profile).unwrap();
        assert!(filters.is_excluded("foo.tmp"));
        assert!(filters.is_excluded("foo.bak"));
        assert!(filters.is_excluded("build/out"));
        assert!(filters.is_excluded("node_modules/x"));
        assert!(!filters.is_excluded("foo.rs"));
    }
}
